# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec1903fd01c76c43fd8aa47310761af0ac7bba32b360ade948e68b1c060eb7e5c4f98f76ce2e93c3b9797274e977a0418a8b8b30f39a5656e34c89d35a8eb08f

test:
  secret_key_base: 562814f89a37239fe4e3da30d880974c421729601ea4b81582f4fd0379fd5c177c7eeabc1fc2d40e72fd876cd1865598d23f90a8bfb6cda485a817cf762a43f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
